### ISSUE TITLE
Release code

### ISSUE THREAD

**Issue by nancheng58** [XuChen0427/Dually-Enhanced-Propensity-Score-Estimation-in-Sequential-Recommendation#1]
Thanks for your excellent work! I am a tyro in the debiased recommendation and want to learn from your code. Could you release your code? Thanks again.

**Comment by xc2017202113** [comment]
I am sorry for the delayed code, because the code is supported on the Recbole platform and but it is updated recently, The code will be released in this week.

**Comment by nancheng58** [comment]
Okay. Thanks for your reply.
